### ISSUE TITLE
Server crashes when someone joins after restarting the server with chunky extended feature enabled

### ISSUE THREAD

**Issue by GabeeeM** [2Lynk/chunky-extended#2]
[crash-2024-01-17_07.04.52-server.txt](https://github.com/2Lynk/Chunky-Extended/files/13959772/crash-2024-01-17_07.04.52-server.txt)

`Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'int net.minecraft.class_2170.method_44252(net.minecraft.class_2168, java.lang.String)'
	at net.fabricmc.chunky_extended.event.OnPlayerJoinHandler.onPlayReady(OnPlayerJoinHandler.java:17)
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48)
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:61)
	at net.minecraft.class_3324.handler$zmd000$fabric-networking-api-v1$handlePlayerConnection(class_3324.java:4011)
	at net.minecraft.class_3324.method_14570(class_3324.java:195)
	at net.minecraft.class_8610.method_52408(class_8610.java:128)
	at net.minecraft.class_8736.method_53043(class_8736.java:20)
	at net.minecraft.class_8736.method_11054(class_8736.java:7)
	at net.minecraft.class_2600.method_11072(class_2600.java:24)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:797)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:779)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:773)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:687)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:840)
`

**Comment by 2Lynk** [comment]
Are you running 1.20+?

**Comment by 2Lynk** [comment]
Fixed it with the latest update. Works for 1.20
